kind: pipeline
name: oati_golang_api_ci

workspace:
  base: /go
  path: src/github.com/${DRONE_REPO}

steps:
- name: build
  image: golang:1.24
  commands:
    - go mod init
    - go get -t
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main
  when:
    branch:
      - develop
      - release/*
      - feature/*
      - master
    event:
      - push