kind: pipeline
name: oati_lambda_ci

steps:
- name: publish_to_ecr_release
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    create_repository: true
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    region:
      from_secret: AWS_REGION
    repo: ${DRONE_REPO_NAME}
    tags:
      - ${DRONE_COMMIT:0:7}
      - release
  when:
    branch:
      - master/*
    event:
      - push

- name: update_lambda_release
  image: amazon/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    AWS_REGION:
      from_secret: aws_region
    ACCOUNT_ID:
      from_secret: aws_account_id
    LAMBDA_NAME_TEST:
      from_secret: lambda_name_test
  commands:
    - export ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$DRONE_REPO_NAME
    - aws lambda update-function-code \
        --function-name ${LAMBDA_NAME_TEST} \
        --image-uri $ECR_URI:release
  when:
    branch:
      - release/*
    event:
      - push
