LogSyslog yes
LogVerbose yes
PidFile /var/run/clamav/clamd.pid
LocalSocket /run/clamav/clamd.sock
FixStaleSocket yes
TCPSocket 3310
TCPAddr 127.0.0.1
ScanMail yes
ScanArchive yes
ScanPDF yes
LogFile /var/log/clamav/clamd.log
